version: '3.9'

services:
  db:
    image: postgres:17
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: valerii
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: bank_rest:0.1
    container_name: bank_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_rest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: valerii
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


volumes:
  db_data:
